import React from "react";

const RewrittenAdCard = ({ rewritten }) => {
  if (!rewritten || !rewritten.headline) return null;

  return (
    <div className="mt-6 p-6 rounded-xl border shadow-md bg-white space-y-4">
      <h2 className="text-lg font-bold text-gray-800 mb-2">🔁 Rewritten Ad</h2>

      <div className="space-y-2 text-sm">
        <div>
          <span className="font-semibold text-gray-600">Headline:</span>
          <p className="text-gray-800">{rewritten.headline}</p>
        </div>

        <div>
          <span className="font-semibold text-gray-600">Description:</span>
          <p className="text-gray-800">{rewritten.description}</p>
        </div>

        <div>
          <span className="font-semibold text-gray-600">Primary Text:</span>
          <p className="text-gray-800">{rewritten.primary_text}</p>
        </div>
      </div>

      <div className="text-xs text-gray-400 mt-3">✨ Generated by GPT</div>
    </div>
  );
};

export default RewrittenAdCard;
